source /usr/share/iwdevtools/qa-cmp.bashrc
source /usr/share/iwdevtools/qa-openrc.bashrc
source /usr/share/iwdevtools/qa-sed.bashrc
source /usr/share/iwdevtools/qa-vdb.bashrc

post_pkg_preinst() {
	qa-cmp_post_pkg_preinst
	qa-openrc_post_pkg_preinst
}

post_pkg_postinst() {
	qa-openrc_post_pkg_preinst
	qa-vdb_post_pkg_postinst
}
